package jdbc;

/**
 * Created by taras.fihurnyak on 2/3/2017.
 */
public interface SqlQuerys {
    String CREATE_DB = "CREATE DATABASE IF NOT EXISTS JavaTrainingDB;";
    String DATABASE_URL = "jdbc:mysql://localhost:3306/";
    String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    String DB_NAME = "JavaTrainingDB";
    String CREATE_OWNER_TABLE = "CREATE TABLE OWNER (ID INT(11) PRIMARY KEY AUTO_INCREMENT, FIRSTNAME VARCHAR (255), LASTNAME VARCHAR (255), GENDER INT (11), AGE INT (11))";
    String CREATE_VEHICLE_TABLE = "CREATE TABLE VEHICLE (ID INT(11) PRIMARY KEY AUTO_INCREMENT, TYPE INT (11), OWNER_ID INT (11),NUMBER VARCHAR (255), MODEL VARCHAR (255))";
    String CREATE_OWNER = "INSERT INTO OWNER(FIRSTNAME, LASTNAME, GENDER, AGE) VALUES(?,?,?,?)";
    String CREATE_VEHICLE = "INSERT INTO VEHICLE(TYPE, OWNER_ID, NUMBER, MODEL) VALUES(?,?,?,?)";
    String GET_OWNER_BY_ID = "SELECT * FROM OWNER WHERE ID=";
    String GET_VEHICLE_BY_OWNER_ID = "SELECT * FROM VEHICLE WHERE OWNER_ID=";
    String UPDATE_OWNER_LAST_NAME = "UPDATE OWNER SET LASTNAME = ? WHERE ID=?";
    String DELETE_OWNER = "DELETE FROM OWNER WHERE ID=?";
    String GET_MAX_OWNER_ID = "SELECT MAX(ID) FROM OWNER ORDER BY ID";

}
